### ISSUE TITLE
Any plans to integrate  with albumentations

### ISSUE THREAD

**Issue by ogencoglu** [nhauber99/degradr#1]
Thanks for the work.

Most pipelines use `albumentations` as it supports a single API for all augmentations. It is battle tested in production and installation is straightforward. This work would reach out to more users if it was integrated with it. Any plans of that?

Also do you have comparisons to `albumentations` augmentations of some of your functions? Especially implementation details and speed benchmarks.

**Comment by nhauber99** [comment]
As of now I don't have any plans for that and integrating it might not even be possible because generating the blur kernels is done as a preprocessing step (and requires the prysm library), the neccessary color space tranformation matrices fall under the license of the libraw library and as far as I'm aware shipping the binaries which use the Intel IPP library is also incompatible with their license.

Performance comparisons are also difficult, because the most time intensive operation is the demosaicing step (specifically with the AHD algorithm) which isn't supported by albumentations at all. All other functions rely on the pytorch implementation so any comparison would be more of a pytorch vs albumentations comparison.

**Comment by ogencoglu** [comment]
Understood, thanks
